"""add users table

Revision ID: ee594e83907a
Revises: 
Create Date: 2026-03-01 22:46:18.154834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee594e83907a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'weight',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('ix_exercises_workout_id'), table_name='exercises')
    op.add_column('workouts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workouts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workouts', type_='foreignkey')
    op.drop_column('workouts', 'user_id')
    op.create_index(op.f('ix_exercises_workout_id'), 'exercises', ['workout_id'], unique=False)
    op.alter_column('exercises', 'weight',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
